### ISSUE TITLE
"No Model Info Passed" Exception for Newly Added Models

### ISSUE THREAD

**Issue by venuswku** [dbuscombe-usgs/CoastSeg#57] opened 2022-08-16 23:59 UTC
When I was trying out different models for the satellite images that I downloaded, there was a `No Model Info Passed` exception thrown for the following 3 models:
- landsat_6229071
- SWED-RGB_6824384
- coast-train-RGB_6950479.

All the other models work.
@2320sharon said these models are some of the newly added models, and it could possibly be an issue with the download function.

### Error Message
```
Called Run Model
Not using the GPU
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
File ~\anaconda3\envs\coastseg\lib\site-packages\ipywidgets\widgets\widget_output.py:103, in Output.capture.<locals>.capture_decorator.<locals>.inner(*args, **kwargs)
    101     self.clear_output(*clear_args, **clear_kwargs)
    102 with self:
--> 103     return func(*args, **kwargs)

Input In [13], in run_model_button_clicked(button)
    117 Ww=zoo_model.get_weights_list(model_choice)
    118 # Load the model from the config files
--> 119 model, model_list, config_files, model_types=zoo_model.get_model(Ww)
    120 metadatadict=zoo_model.get_metadatadict(Ww,config_files, model_types)
    121 # # Compute the segmentation

File ~\Projects\CoastSeg\CoastSeg\zoo_model_module.py:64, in Zoo_Model.get_model(self, Ww)
     62 model_types = []
     63 if Ww == []:
---> 64     raise Exception("No Model Info Passed")
     65 for weights in Ww:
     66     configfile = weights.replace('.h5', '.json').replace('weights', 'config')

Exception: No Model Info Passed
```

### Replicate Issue
- Checkout to this branch: [https://github.com/venuswku/CoastSeg/tree/no-model-info-passed-exception](https://github.com/venuswku/CoastSeg/tree/no-model-info-passed-exception).
- Run CoastSeg using this notebook: `app.ipynb`.
- This is a visual of the ROIs that I selected on the map.
![image](https://user-images.githubusercontent.com/71415129/185003779-2786c23f-c887-4f84-a075-7dc057b7710f.png)
- The satellite images that were downloaded can be seen in [https://github.com/venuswku/CoastSeg/blob/no-model-info-passed-exception/data.zip](https://github.com/venuswku/CoastSeg/blob/no-model-info-passed-exception/data.zip).

**Comment by 2320sharon** [comment] 2022-08-22 22:19
Hey Venus I have been trying to replicate the bug on my computer with no luck. Can you check the folder called `downloaded_models` within the `coastseg` folder and tell me if you see any of those models you listed in the issue?

If the models are not there it means there was an issue downloading them from Zenodo. Thanks again for finding this bug! 🐛

**Comment by venuswku** [comment] 2022-08-22 22:23
![image](https://user-images.githubusercontent.com/71415129/186029140-41afc9c5-ab6c-4a9c-9567-0b45f0bf127b.png)
It looks like all the models are there... Let me delete the models and try downloading again to see if the error pops up.

**Comment by 2320sharon** [comment] 2022-08-22 22:36
Strange, and the folders aren't empty right? Can you share a screenshot of the contents of `landsat_6229071`?

**Comment by venuswku** [comment] 2022-08-22 22:45
![image](https://user-images.githubusercontent.com/71415129/186031526-c044267d-6842-484b-a0b9-94e21611f18a.png)
Oh! Maybe I didn't complete the some downloads because I was running the models pretty quickly.

**Comment by 2320sharon** [comment] 2022-08-22 22:46
If that is the only folder in landsat_6229071 then it means the model didn't get unzipped which means the code had no idea how to read the model

**Comment by 2320sharon** [comment] 2022-08-22 22:48
Thank you for running the model again 😄 
 Can you elaborate on what you mean by `you were running the models quickly` so I can try to figure out what went wrong?

**Comment by venuswku** [comment] 2022-08-22 22:53
I think I tried to run different models on the selected data while the previous one was still in the middle of unzipping. I didn't know there was an unzipping step back then.

**Comment by 2320sharon** [comment] 2022-08-22 22:56
If the model was still in the middle of unzipping it should have prevented you from running the other models. Now that I know how to replicate the bug properly let me give it a try.

**Comment by 2320sharon** [comment] 2022-08-22 23:22
So I cannot seem to replicate your bug, but I think I know a way to fix it. I'll be working on the solution today and tomorrow.
Thanks again for finding it 🌟

**Comment by venuswku** [comment] 2022-08-22 23:30
I ran all the models again and made sure the unzipping step finished each time. This is what I encountered this time:
- When I ran with landsat_6230083, I get a TensorFlow error that I didn't see last time.
![image](https://user-images.githubusercontent.com/71415129/186032050-07479eb0-a8e6-4787-848a-875233112103.png)
- You already know this but just a little reminder that the TensorFlow error for running SWED-MNDWI_6824342 is there.
![image](https://user-images.githubusercontent.com/71415129/186034741-1dc3b381-095f-47fc-894a-5b0dc60eb18a.png)
- I also didn't see the following warning when I ran coast-train-RGB_6950479 last time.
![image](https://user-images.githubusercontent.com/71415129/186036127-915c22d0-2a99-4a2f-9f5a-7df3efb65708.png)
- The other models didn't have any errors. I was wondering if running each model would produce some file in the `out` folder because I only got 3 images after running all 6 models.
![image](https://user-images.githubusercontent.com/71415129/186036961-b215d2c3-4125-403d-a26f-a0629150b8e3.png)

**Comment by 2320sharon** [comment] 2022-08-22 23:32
Quick question did you run all of the models on the same folder `segmentation_data_2022_08_22_15_hr_35_min_23`?

**Comment by 2320sharon** [comment] 2022-08-22 23:35
I've encountered the TensorFlow model errors quite a few times but I'm not sure how to fix them yet. 
@dbuscombe-usgs  @ebgoldstein  do these warning messages look like they come from how the models were constructed or the data being passed into the models?

**Comment by venuswku** [comment] 2022-08-22 23:36
Yes, I ran all the models on the same folder! I didn't want to take up extra storage to download ROIs again. 😂 So maybe the output files got overwritten?

**Comment by 2320sharon** [comment] 2022-08-23 00:00
So you didn't click the  `use data` button in between running the models and just ran them all in the same folder. I've never done that before. That might explain the strange behavior.
I'll make a note to test that too 🥼

**Comment by venuswku** [comment] 2022-08-23 00:06
Oh, I never thought of clicking the `Use Data` button in between running models since I thought it only needed to be loaded once. I'm coming up with all types of weird test cases haha

**Comment by 2320sharon** [comment] 2022-08-23 00:11
When I was writing it I assumed our end user would only be using one model for each dataset. 

- [ ] Add instructions to tell user they shouldn't run all the models on a single folder or they might overwrite their results.

- [ ] Test what happens when you run multiple models on a single folder

**Comment by venuswku** [comment] 2022-08-23 00:17
^ And make sure user waits for the downloaded model folder to be unzipped.

**Comment by dbuscombe-usgs** [comment] 2022-08-26 18:50
How can I help here? @2320sharon what errors do you get from Tensorflow? Are you referring to the warnings about tracing? If so, it looks like it suggests a few things to try, but my hunch is that you are passing it a 1-band image tensor e.g. (1,256,256,1) when it expects 3-band (1,256,256,3). That may be either because the functions should be modified to force usage of 3 bands, or because you are using a model that is not designed for this data. 

also, this repo contains an older version of CoastSeg, way downstream of the latest version .... let's post issues to the most current repo

**Comment by dbuscombe-usgs** [comment] 2022-08-26 18:55
Oh, I see all the issues are here. That's ok, then - scratch my last comment. Issues can live here

**Comment by 2320sharon** [comment] 2022-08-26 19:33
@dbuscombe-usgs It looks like one of the Tensorflow errors was caused by running the `SWED-MNDWI_6824342` model on RGB imagery which would explain why the input shapes don't match and thus the error.
I'm not sure about the `tracing` warning messages but I think we can put these issues on the back burner for now.

**Comment by dbuscombe-usgs** [comment] 2022-08-30 01:38
I'm not concerned by the tracing warnings at the moment, and I'm hoping a combination of a) better docs, and b) some progress to check the validity of a model application. On the latter, it should be possible to check the N_DATA_BANDS in the model config file (or model card) against the number of bands in the sample imagery. Perhaps it could be a box that the user indicates what style of model (RGB versus MNDWI versus other), and that limits the available models 

I'm prepping things so I can try to systematically step through testing of each model. I'll try to thoroughly document things as I go. I'll also try to make more solid suggestions about what b) above could look like

**Comment by 2320sharon** [comment] 2022-09-02 22:07
I'm going to close this issue and create two new ones.
1. Run multiple models on one folder. This issue will hinge on updating doodleverse utils.
2. Another issue to create an option to select RGB or MNDWI model that limits the model options available to the user.

**Closed by 2320sharon** 2022-09-02 22:07 UTC
Labels: bug
